### ISSUE TITLE
Exception on Chordious first-run

### ISSUE THREAD

**Issue by jonthysell** [jonthysell/Chordious#18]
Exception details: com.jonthysell.Chordious.Core.ObjectIsReadOnlyException: The ChordiousSettings could not be modified because it is marked read-only.
   at com.jonthysell.Chordious.Core.InheritableDictionary.Set(String key, String value)
   at com.jonthysell.Chordious.Core.InheritableDictionary.Set(String key, Object value)
   at com.jonthysell.Chordious.WPF.MainViewModelExtended.set_IsFirstRun(Boolean value)
   at com.jonthysell.Chordious.WPF.MainViewModelExtended.FirstRun()
   at com.jonthysell.Chordious.WPF.MainViewModelExtended.<<OnLoaded>b__0>d__1.MoveNext()

**Comment by jonthysell** [comment]
On a new install, there's no user config file, so it doesn't load it. So when it tries to set the first-run flag in AppVM, it tries to update the App config, which is read-only.

Solution is to, if no user config exists, save the blank user config to disk first, so that the read will happen and succeed.

Also need to catch any exception trying to load that user config (like say, if it's a blank file) and give the user a dialog, with the option of starting Chordious anyway (maybe backing up the config?)
